[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = [
  "cd backend",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"